version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - rede-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=estabelecimento
networks:
  rede-mysql: